### ISSUE TITLE
On click of next arrow, prev arrow, manual date inputs, calendar shifts to top left of browser

### ISSUE THREAD

**Issue by stephendverret** [dangrossman/bootstrap-daterangepicker#1021]
The calendar gets shifted to top: -148px on click of any next arrow, prev arrow, manual date inputs. Can not trace the issue. Please advise.

**Comment by dangrossman** [comment]
How would one trace your issue without seeing your page?

**Comment by stephendverret** [comment]
http://www.thriveacadiana.com/

If you click "When" and then click "Custom Dates" the daterangepicker will display. I have overridden the issue with positioning and "!import". This is a very hacky way of handling this and would rather not have to chase the calendar around. If you inspect the daterangepicker and turn off the important positon calls you will see what I am talking about.

Thank you.

**Comment by dangrossman** [comment]
The issue is that you've attached the calendar to a dropdown menu item which disappears as soon as you trigger the date picker. The picker computes its position based on the location, width and height of the HTML element it's attached to. The position is re-computed when you interact with the picker or the window, so it always stays aligned with your element correctly. Your element, however, is changing size and being hidden while the picker is open. My best suggestion would be to not embed the picker in a dropdown, and instead let the picker be your dropdown as it was meant to be. Set your predefined ranges as options, rather than making a separate list on your website, and style it to look how you want.
