### ISSUE TITLE
Clicked range label is not active if there exists multiple identical start dates and/or end dates

### ISSUE THREAD

**Issue by jliang6** [dangrossman/bootstrap-daterangepicker#1037]
The problem is at line 1335 for release 2.1.19:

`if (this.startDate.format('YYYY-MM-DD') == this.ranges[range][0].format('YYYY-MM-DD') && this.endDate.format('YYYY-MM-DD') == this.ranges[range][1].format('YYYY-MM-DD')) {`

It blindly takes the very first complete matched start dates and end dates pair and assign the range label to be active.

It should be like:

`if (range === this.chosenLabel && this.startDate.format('YYYY-MM-DD') == this.ranges[range][0].format('YYYY-MM-DD') && this.endDate.format('YYYY-MM-DD') == this.ranges[range][1].format('YYYY-MM-DD')) {`

This will check both start dates and end dates pair for equivalence AND make sure the labels match as well.

**Comment by dangrossman** [comment]
If a user selects dates using the calendars, and the match one of the predefined ranges, I want that range to become highlighted. That's why I don't compare the "chosen label", because they may not have made their selection by clicking any predefined range label. Feel free to submit a PR that keeps that in mind while improving this code if you'd like.
