### ISSUE TITLE
Inconsistent results when picking date+time using different methods

### ISSUE THREAD

**Issue by robmarston** [dangrossman/bootstrap-daterangepicker#1058]
I'm seeing in consistent results when selecting the date and time using different methods in the latest release (2.1.19). Here are the options I'm using: 

```
startDate: moment.utc().startOf('day'),
endDate: moment.utc().endOf('day'),
ranges: {
     'Today': [moment.utc().startOf('day'), moment.utc().endOf('day')]
}
```

In all of the instances below startDate.toISOString() is correct (2016-04-20T00:00:00Z):

* On page load
* If I open the daterangepicker and click Apply
* If I open the daterangepicker and click Today

That said, if I open the daterangepicker and click April 20th twice and click Apply and/or attempt to manually enter the times the value of startData.toISOString() is incorrect (2016-04-20T07:00:00Z).

**Comment by nip3o** [comment]
I believe the problem is that selected dates are always using the local timezone, not UTC. I think that is a bug, and there are several issues regarding this as well (for example #343), but they have been closed without much comment. A workaround is to be to "hack the timezone info away" from the moment-object, as described in the mentioned issue.

**Comment by robmarston** [comment]
@nip3o that's exactly how we worked around the issue -- thanks for the suggestion! The product requirement (from my client) it to use UTC unfortunately, an edge-case perhaps but buggy nonetheless. Our workaround did introduce some new issue where the calendar and dropdown selections don't always coincide with the value of the main input. Anyway, hopefully the team can take a look or I can find some time to fork and fix myself :)

**Comment by k-funk** [comment]
Not sure why this issue was closed. It's definitely still a bug.
If I follow the examples in the documentation, but use `moment().utc()` in place of `moment()`, I get an odd display bug where the next day is also included while hovering:
![screen-shot-2017-04-21-at-4 18 30-pm](https://cloud.githubusercontent.com/assets/1933021/25298903/893ad0a8-26ae-11e7-95ef-254a6796e5a0.jpg)
