### ISSUE TITLE
Predefined Ranges not working for “Today” only for first time but working with other options

### ISSUE THREAD

**Issue by syednizamudeen** [dangrossman/bootstrap-daterangepicker#1071]
When choosing Dates i store it in `HTML` in separate `<div>` elements as `Start Date` and `End Date`. The plugin is working fine. One thing i don't understand is

> Choose `Today` from Dropmenu. Only for the first time its not passing any data to `<div>`. If i choose any other option for the first its working fine.

Find JSFiddle [here](https://jsfiddle.net/tpsdwp8j/1/)

What i'm trying to do is? On Date selection write `startdate` and `enddate` to `<div>`.

**Comment by dangrossman** [comment]
Your callback function is only called when the start and end dates change.

Since you did not set any initial `startDate` and `endDate` in your options, they default to today's date.

Clicking on "Today" when "Today" is already selected is not a change, so your code is not invoked.

You can watch the `apply.daterangepicker` event instead if you want to know they clicked the same range twice.

**Comment by fahimku** [comment]
use onEvent instead of onCallback
it will works.
