### ISSUE TITLE
How to clear selected predefined range programmatically

### ISSUE THREAD

**Issue by toddhickerson** [dangrossman/bootstrap-daterangepicker#1104]
I see in the example how to clear the date field on the cancel.daterangepicker event. However, the previously selected predefined range is still selected. I've tried removing the "active" css class from the selected <li> but calling that from angular does not seem to work. The selection is still persisted. Any ideas or examples would be appreciated. (FYI...I have autoApply set to false and am clearing the date input and startDate/endDate with a button outside the date picker.) Thank you in advance...and thanks for giving us such a great component!

**Comment by dangrossman** [comment]
You can't clear the startDate/endDate. There is always a start/end date selected internally. If those dates match one of the predefined ranges, that range will be highlighted. Otherwise, "Custom Range" will be highlighted. There is no scenario in which none will be highlighted.

**Comment by ldwnt** [comment]
Consider this case: user selects "Past 30 days" (assume that's Jul. 22 to Aug. 20) but program finds only query from Aug. 1 to Aug. 20 is accepted. So startDate/endDate is set to Aug. 1/20 instead and shown in the input box. At this point, label "Custom" instead of "Past 30 days" should be highlighted. Unfortunately, startDate/endDate seem not to be watched and "Past 30 days" is still highlighted. If the not-watching behavior is intended, I do think it's necessary to provide an API to highlight the selected range label.

**Comment by mtereschenko** [comment]
"@There is no scenario in which none will be highlighted." - clear filters with multiple daterangepickers
