### ISSUE TITLE
datepicker hidden behind model

### ISSUE THREAD

**Issue by TrplM** [dangrossman/bootstrap-daterangepicker#1107]
Datepicker is hidden behind model when used in a modal form.

**Comment by System64** [comment]
To fix this you can increase the z-index in the **daterangepicker-bs3.css** file. I have changed mine to
```
.daterangepicker.dropdown-menu {
  max-width: none;
  z-index: 9999999; 
}
```

**Comment by MubienN** [comment]
Thanks, I have done this for now.

However a scenario still exists where using z-index will cause the datepicker to be above a modal notification/warning instead of behind.  This can be manged by then increasing z-index on the notification modals etc.

However I think, a more elegant solution will be to inherit the parent z-index, which I think should then draw it above the calling modal and below the notification models because of the stacking order.

But :( I don't have a clue if this is possible or how to go about it, :) and I may just be nitpicking a stupid issue

**Comment by dangrossman** [comment]
Thanks for leaving a solution @System64
