### ISSUE TITLE
Timezone issue after changing month in custom range selection

### ISSUE THREAD

**Issue by Fensterbank** [dangrossman/bootstrap-daterangepicker#1108]
I found a bug related to timezoning after the custom range month is changed.
It can be reproduced on your official demo site.
It seems this issue only occurs if the month of a previously selected custom range is changed in the selection afterwards.
I'm in CEST (UTC+ 2 hrs).

It's always reproducable for me with e.g. following steps:

## 1.)
When selecting a predefined range "Last Month", following moment instances will be generated:

**May 1, 2016 - May 31, 2016**
From:
`Object { _isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-04-30T22:00:00.000Z, _isValid: true }`
To:
`Object { _isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-05-31T21:59:59.999Z, _isValid: true }`

This is the expected result!

## 2.)
Then I switch to `Custom Range` and select new start **and** end date, following moment instances will be generated:

**July 1, 2016 - July 31, 2016**
From:
`Object { _isAMomentObject: true, _i: Array[6], _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-06-30T22:00:00.000Z, _isValid: true }`
To:
`Object { _isAMomentObject: true, _i: Array[6], _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-07-31T21:59:59.999Z, _isValid: true }`

This is the expected result!

## 3.)
Now I change the custom range. If I stay in the current month, it's no problem.
But as soon as I change the month by using the month selection dropdown, all following dates will be created in the wrong timezone.
So if I now change my Custom Range to **February 1, 2016 - February 29, 2016**, following moment instances will be generated:

From:
`Object { _isAMomentObject: true, _i: Array[6], _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-01-31T23:00:00.000Z, _isValid: true }`
To:
`Object { _isAMomentObject: true, _i: Array[6], _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-02-29T22:59:59.999Z, _isValid: true }`

Here both dates are now shifted an hour. It's still not a UTC moment, but wrong date times have been generated.

**Comment by dangrossman** [comment]
Feel free to investigate/fix. I doubt I'll ever have time to track this down. There is no timezone-related code in the entire library.

**Comment by drakej** [comment]
This is most certainly a bug. The widget may seem timezone unaware but really it's using the user's browser timezone. So if you pass in predefined ranges or want to take in input in a timezone that is not what the user's browser is set to, it breaks.

Whether or not you want to manage timezones, you really opened that can of worms when you allowed predefined ranges based on current time. What does "Today" mean without the context of what time and day it currently is? Today will differ for someone in their current browser timezone from all of the other timezones. Let's say it's currently 1 AM UTC, then it's 4 PM PDT on the prior day. So in that case yesterday and today will differ based on the timezone.

The bug is less apparent if you don't have the time ticker turned on, but it's very apparent when you do. Just because it's less noticeable and has less impact on "dates", it still is there, broken, and hidden nonetheless.

**Comment by dangrossman** [comment]
Nobody said there is no bug. It's just not one I will likely ever be able to fix, since it's so fundamental, yet can be worked around. This is a 2012 quick side project in maintenance mode.

**Comment by drakej** [comment]
OK fair enough. Sorry I guess I misunderstood. With that said, would you prefer if I take some time to track down a fix for this and make a push request down the road?

Do you internally use moment js? I'm thinking you don't need to actually make all of the code timezone aware but just provide a UTC toggle on it. Since I ran into this problem by setting predefined ranges with moment().utc(). 

Also I think this bug was introduced in 2.x, since the older version of the widget seemed to handle it. I need to do some more debugging and research on it though so while I know it used to work, I need to give you more specific changes that may have affected it.

**Comment by Fensterbank** [comment]
At the moment, I'm not sure, if it's really a timezone issue or if there is a calculation error somewhere.
After all I know the shifted time in **step 3** `Object { _isAMomentObject: true, _i: Array[6], _isUTC: false, _pf: Object, _locale: Object, _d: Date 2016-01-31T23:00:00.000Z, _isValid: true }` does still have a timezone offset of two hours in my case.

So maybe there is somewhere added an hour mistakenly and it doesn't have anything to do with timezones. But in the wrong timezone this could also affect the Date only selection.

Yes, internally `moment.js` is used. In my short debugging session I did not found the source of this bug and timezone things or time calculation aren't really done in this code.

Unfortunately I don't have the time to dive deep into this code, I use only date range selection and could easily workaround. I'm sure this bug is really annoying if date and time selection is used.

**Comment by dangrossman** [comment]
Closing this since I don't think it serves any purpose. Nobody is going to take any action on this issue.

**Comment by drakej** [comment]
This has been closed but I found a workaround due to Dan's insistence on not providing an option to use UTC times internally inside of the customer calendar logic.

```
    function(start, end) {
        var offset = start.utcOffset();
        start.utc().add(offset, 'm');
        
        offset = end.utcOffset();
        end.utc().add(offset, 'm');
        
        $('#daterange span.range').html(start.format(range_format) + ' - ' + end.utc().format(range_format));
        $('#daterange_start').val(start.format(range_format));
        $('#daterange_end').val(end.utc().format(range_format));
    }
```

This is my user callback. To get around the fact that the calendar sends back moment objects in the local timezone of the browser, I store the offset from that timezone to UTC locally then modify the moment object by converting it to UTC and finally taking that original offset and adding it so that it shifts to the same time and date that would have been selected had the original moment object been in UTC mode.

This works because there's no "relative time" issue when selecting explicit date and times inside of the calendar. Predefined ranges will still need to use UTC mode moment objects since they can be relative to current time and it would create problems if they were local and then converted by this function. 

So to be clear, this will only work for custom ranges since predefined ranges are not always an explicit range and may be relative to the current time.

Here's an example of some predefined ranges I use to make everything line up and work as expected:

```
        ranges: {
            'Last 2 Hours': [moment().utc().subtract(2, 'hours').startOf('hour'), moment().utc().startOf('hour')],
            'Today': [moment().utc().startOf('day'), moment().utc().add(1, 'days').startOf('day')],
            'Last 2 Days': [moment().utc().subtract(1, 'days').startOf('day'), moment().utc().add(1, 'days').startOf('day')],
            'Last 7 Days': [moment().utc().subtract(6, 'days').startOf('day'), moment().utc().add(1, 'days').startOf('day')]
            ,'Last 30 Days': [moment().utc().subtract(29, 'days').startOf('day'), moment().utc().add(1, 'days').startOf('day')],
            'This Month': [moment().utc().startOf('month'), moment().utc().add(1, 'month').startOf('month')],
            'Last Month': [moment().utc().subtract(1, 'month').startOf('month'), moment().utc().startOf('month')]
        },
```

Those utc() calls make sure that all of the objects are in UTC mode and when my callback gets them the offset is already 0 so no change is made.

**Comment by drakej** [comment]
Since I realized I was using a predefined variable for the date formatting (which has no actual impact on the fix itself). Here's what I have range_format set to:

```var range_format = 'YYYY-MM-DD HH:mm z';```
