### ISSUE TITLE
How to dynamically update predefined range

### ISSUE THREAD

**Issue by garyelephant** [dangrossman/bootstrap-daterangepicker#1137]
As far as I know, `ranges` are defined at first by `fixed time`, if time elapses 10 minutes when I click on `Today`, which end date is moment(), calculated by 10 minutes ago, `Today` will not include these 10 minutes.

```
$('#reportrange').daterangepicker({
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

```

How to get correct time range by `NOW`, not the time daterangepicker initialized ?

**Comment by dangrossman** [comment]
Calculate it in your callback function, which is triggered after someone clicks on a date range

**Comment by Shaffron** [comment]
You should refresh ranges values.
In my case, I make a function that refresh ranges has interval.
You just give new array to $('your_daterangpikcer_tag').data().daterangepikcer.ranges = {new array};
It's done.

**Comment by msedatgungor** [comment]
@dangrossman It still won't show the right information on case when user selects a range for the first time. Say, the daterangepicker is loaded at 11:53, so initially "Today"s endDate is also 11:53. When user selects "Today" as range 2 minutes later (11:55), even though you might update the ranges in callback, the handler will take consider as predefined range Today's end date as 11:53.

So, calculating it in callback function will be visible to user at least on second date/predefined range selection and it will show wrong date information again because of this problem.

The solution should also calculate range values before the user clicks the apply button, or clicks a predefined range. Daterangepicker should call its callback after the ranges are calculated and updated.
