### ISSUE TITLE
Allow the startDate and endDate to be null

### ISSUE THREAD

**Issue by multiwebinc** [dangrossman/bootstrap-daterangepicker#1141]
By default if no `startDate` or `endDate` are provided they default to `moment().startOf('day')` and `moment().endOf('day')` respectively. It would be great to allow them to be set to `null` so that no dates are highlighted if none are provided, similar to how it is done here:

No dates selected:
![expedia_calendar](https://cloud.githubusercontent.com/assets/901732/16243523/e306029a-37b4-11e6-9a44-8d5579315369.png)

Dates selected:
![expedia_calendar1](https://cloud.githubusercontent.com/assets/901732/16243559/1cfcccfe-37b5-11e6-98c5-cdc11fa6279c.png)

**Comment by dangrossman** [comment]
Yes, that's a common feature request, but would require changing just about everything internally here. There are always dates selected in this library. Your best bet if you want nullable selections is to choose a different library.

**Comment by multiwebinc** [comment]
If I were to work on this, is this something that you would want to include in your code?

**Comment by dangrossman** [comment]
I think what you'd end up with is basically a completely new library, since assumptions about the state of those variables are built into virtually every one of this library's 1500+ lines. I don't plan to replace the entire library with someone else's, and I'm not sure it makes sense to rewrite this for that purpose when there are other date range pickers you could use, so I'd have to say the answer is no.
