### ISSUE TITLE
Unnable to set empty date

### ISSUE THREAD

**Issue by AlekseiSkrebkov** [dangrossman/bootstrap-daterangepicker#1180]
We would like to use this component for filtering table date by date field. We really like it but the only problem is it doesn't allow to set empty date. So if user doesn't want to filter by date we can't use this component. 
What is the reason why you implemented this restriction:
```
elementChanged: function() {
            if (!this.element.is('input')) return;
            if (!this.element.val().length) return;
            if (this.element.val().length < this.locale.format.length) return;
```

Is it possible to support empty date?

**Comment by witalobenicio** [comment]
Why you closed this? How can I set empty date?

**Comment by dangrossman** [comment]
Create a clear button: http://www.daterangepicker.com/#ex5

**Comment by michaelsogos** [comment]
Dear @dangrossman ,

The solution you provided works but still remain an issue.

Also we are using this component as filter for a table, and if you click on "Clear" button (like in the example you provided) it works but the range selected still be visible if user open again calendar control, and this confuse our users. The issue itself not affect our logic because the picker value is "", it is just an visual issue that confuse users.

**Comment by dangrossman** [comment]
You have two choices: use a different date picker, or alter this one to meet your requirements.

**Comment by michaelsogos** [comment]
In a different post i found that we can use setStartDate and setEndDate to new Date().
In this way the control reset previous selection and show "today" selected.

This is just a workaround that works for us. Obviously could be better if we can have empty date.
