### ISSUE TITLE
Clicking active range after clearing does nothing!

### ISSUE THREAD

**Issue by dmason30** [dangrossman/bootstrap-daterangepicker#1182]
@dangrossman If you load a page with today range set, that is fine the active range is highlighted as expected:

![image](https://cloud.githubusercontent.com/assets/20278756/17296834/011c6fba-57fb-11e6-9094-68783b7b9a40.png)

However then if you click the clear button and go back the today option is still active and when you click it the field is not repopulated.

![image](https://cloud.githubusercontent.com/assets/20278756/17296900/3ce22058-57fb-11e6-98a8-c1b88d2c82fa.png)

**Comment by dangrossman** [comment]
This library has no "clear" button, you made that by renaming the cancel button. Internally, "today" is still selected. Your callback function is only triggered when a new date range selection is made. Clicking the current selection is not a new selection. If you want to know the same selection was clicked twice, you can listen for the `apply.daterangepicker` event instead of using a callback.
