### ISSUE TITLE
Week numbering is off

### ISSUE THREAD

**Issue by LevelUpLab** [dangrossman/bootstrap-daterangepicker#1196]
When displaying the week numbers it is currently off by one week. Today (August 10th 2016) is shown as week 33 while it is in fact week 32.

Edit: Perhaps because 2015 was a bit special with 53 weeks whereas 2016 has the regular 52?

**Comment by dangrossman** [comment]
`moment.week()` says this is week 33 locally, while `moment.isoWeek()` says this is week 32 under the ISO calendar.

If you want to use the ISO week number, set `showISOWeekNumbers: true` in your settings

**Comment by LevelUpLab** [comment]
My bad! Thanks for quick fix

**Comment by LevelUpLab** [comment]
Actually, I was a bit too quick there. Setting it to ISOweek (also on your example page http://www.daterangepicker.com/#options) displays the current week as 31. So I get 31 and 33, but it is actually 32. 

What am I doing wrong?

**Comment by dangrossman** [comment]
Here's the ISO week calendar:

http://www.epochconverter.com/weeks/2016

The row starts with the date August 7th which is in ISO week 31.

If you set the week to start on Monday instead of Sunday, then I think August 8th would be the first day in the row and we'd be in week 32.

I think this is correct...
