### ISSUE TITLE
dinamically setted minDate does not make the picker open in the right month

### ISSUE THREAD

**Issue by CViniciusSDias** [dangrossman/bootstrap-daterangepicker#1283]
When I dinamically set the minDate of my picker after the page has been loaded, the picker does not open in the right month (or year, if it's the case).

Here is an example:
<img src="http://uploaddeimagens.com.br/images/000/757/613/full/picker.jpg" />

My minDate  was set to 01-01-2017 but the picker did not open on January.

**Comment by dangrossman** [comment]
Did you also set a `startDate`? What does "dinamically set" mean? Code would help.

**Comment by CViniciusSDias** [comment]
By dinamically set, I mean I set after the plugin has been initialized. I have a check in and check out picker, and the minDate of the check out plugin must be bigger than the date selected on check in. But, I can't set the date with `startDate` because the user has to pick it himself.

**Comment by dangrossman** [comment]
There is no method to set `minDate` after initializing the plugin.

**Comment by CViniciusSDias** [comment]
This does the job:
$(selector).data('daterangepicker').minDate = desiredDate;

**Comment by dangrossman** [comment]
That is not a way to set the minDate, which is why the UI does not appear correct. You are changing internal state that is not supposed to be touched by an external user (you). 

You should call `$(selector).daterangepicker({ options, callback })` with your new minDate and any other options to make changes to them.
