### ISSUE TITLE
Changed behavior from 1.x

### ISSUE THREAD

**Issue by gaui** [dangrossman/bootstrap-daterangepicker#1329]
Why did the behavior change between 1.x and 2.x? In 1.x you first chose left date for "date from", then right date for "date to". Now you can choose right date for "date from" and vice versa. This is very confusing.

Behavior from 1.x:

![](http://i.imgur.com/mWvmADh.gif)

Behavior from 2.x:

![](http://i.imgur.com/5bGNJaT.gif)

Could this be optional?

**Comment by dangrossman** [comment]
Because I could find no other date range pickers on the web that worked that way.

They all work like 2.x: what end of the date range you're choosing depends on the state, not which side calendar you're clicking.

Examples: Google Flight Search, Google Analytics, Expedia, Booking.com, Hotels.com, jQuery Datepicker, TripAdvisor...

If you prefer the 1.x behavior you can still use the 1.x code, but I think your users will find it very confusing.

**Comment by gaui** [comment]
Ok thank you. :)
