### ISSUE TITLE
How to disable 'Today' selection?

### ISSUE THREAD

**Issue by eiabdulsamad** [dangrossman/bootstrap-daterangepicker#1368]
Hi,
Default today's date highlighted when open the daterangepicker first time, how to clear it?  

Please refer this screenshot: 
http://image.prntscr.com/image/40077cca17b64f8eb5f20608737530b4.png

Thank you

**Comment by Arkiliknam** [comment]
Similarly, using singleDatePicker mode, any existing date is overwritten when you first launch the datepicker with the current date.

**Comment by dangrossman** [comment]
@eiabdulsamad Some date must always be selected. If you do not provide a `startDate` and `endDate` options, they will default to today's date.

@Arkiliknam Please do not comment on unrelated issues with a different question/issue. What you've said is untrue. If you attach the picker to a text input and it contains a date in a format matching your `locale.format` setting (MM/DD/YYYY by default), then that becomes the picker's `startDate` rather than the default. You can also set `autoUpdateInput: false` to not have this widget manage the content of your form input at all.

**Comment by Arkiliknam** [comment]
@dangrossman Thanks for such a speedy response and such a great control. I'm sure I have had issues around this area as I've spent several hours trying to implement your control into a solution. When I get some time I'll detail exactly what issues I was having as a new issue. It may well be down to my own usage but I am fairly confident I have implemented the control as per your documentation.
