### ISSUE TITLE
Dates with only month and Year.

### ISSUE THREAD

**Issue by atlanticstarr1** [dangrossman/bootstrap-daterangepicker#1390]
Can you suggest a configuration to show only the month and year ? e.g. Jan 2017, Feb 2017. I do not want to see the calendar where i can select days.

**Comment by dangrossman** [comment]
You don't need a javascript date range picker widget, 90% of which is generating and managing calendars, you need some HTML `<select>` elements on your webpage.

**Comment by vibs2006** [comment]
@dangrossman sir I agree that we can simply use a dropdown (select) option to display months but there are some conditions like if the person selects current year then we don't want to display months MORE than the current month. So a lots of javascript / jquery needs to be added from our side to impliment those changes. A simple and single widget where we can dynamically control these things would be really great. 

For example I have a requirement where sometimes I have to show Date Range Picker, sometimes normal Date Picker (without range with single value only). So to cater these two options i can simply tweak your JSON Options however if I have a requirement where I need to ONLY display then the problem comes because in that case I have to first HIDE your widget and then make my dropdown visible!
