### ISSUE TITLE
minimum span

### ISSUE THREAD

**Issue by rolandoldengarm** [dangrossman/bootstrap-daterangepicker#1419]
I know, this has been brought up before, but there are two PR's that solve this problem: https://github.com/dangrossman/bootstrap-daterangepicker/pull/171 and https://github.com/dangrossman/bootstrap-daterangepicker/pull/427 
However those PR's have been closed without merging?

See all issues:
https://github.com/dangrossman/bootstrap-daterangepicker/issues/1287
https://github.com/dangrossman/bootstrap-daterangepicker/issues/1282
https://github.com/dangrossman/bootstrap-daterangepicker/issues/336
https://github.com/dangrossman/bootstrap-daterangepicker/issues/221

So apparently there is a  need for this option. We use the date range picker in a booking site, and we need t enforce a minimum range.

Is it possible that one of the PR's is being merged? I'm happy to submit a new one, but only if it's being looked at and not just closed.

Thanks. Great work!

**Comment by dangrossman** [comment]
`this.dateLimit` gets referenced 11 times throughout the code, where the referenced patch uses the new `this.dateLimitMin` just twice. What do you think the chances of that being bug-free are, versus there being up to 9 times the `dateLimitMin` isn't getting applied when someone will expect it to be if it's added to the list of options? Along with changing dozens of lines of code because some auto-formatter disagreed with someone else's auto-formatter, making it hard to review what actually changed, are the reason this was passed over. I don't have time to invest lots of time into reviewing and fixing partial patches that'll almost definitely create more bugs, so I pass on all but very straightforward or very thorough PRs. I also only review PRs a few times a year. It's a five year old widget that's downloaded thousands of times a week, so a couple people over the course of years interested in an option is probably below the threshold to be worth carrying around and maintaining that option forever. There's nothing wrong with adding options/features to your own copy without them being in the original branch too.

**Comment by lucasklaassen** [comment]
@dangrossman I see where you're coming from, just keep in mind there are developers out there that would love to help maintain this project and help vet some of these PR's. Thanks for taking the time to create this open source repo, this widget has saved me a lot of time. More than willing to help out maintain it!

**Comment by rolandoldengarm** [comment]
@dangrossman I appreciate your stance, you can only merge high quality PR's.
I'm happy to submit a PR that meets your standard. Is there any developer documentation? Automated tests? 
Or will you never accept a PR that introduces this feature?
