### ISSUE TITLE
AutoApply with singleDatePicker and no timePicker

### ISSUE THREAD

**Issue by fabiopenagoli** [dangrossman/bootstrap-daterangepicker#1433]
I need to show a SingleDatePicker calendar with no TimePicker but with the APPLY / CANCEL buttons for date confirmation.
It seems not working if I set AutoApply = false.
I need to autoUpdateInput but not AutoApply the selection.

Thanks so much!

**Comment by dangrossman** [comment]
Then you will need to customize the code or make your own confirmation buttons. 

This library assumes that if someone is presented with a calendar to choose a single date, they are capable of clicking the date they intend the first time. They can always click the input again if they misclick. No confirmation button is shown in this case.

**Comment by garriscp** [comment]
This describes my exact issue.  I am using autoUpdateInput false because I need the value to be initialized as an empty string.  It's for a form and the user needs to be able to leave this field blank (instead of submitting some default date value like "today").

In this case, it's my understanding that I will need the cancel (updating the label to 'clear' as described in your doc) and apply buttons and use the event callbacks to update the selected value.

I will edit the code to allow this to work for my use case.
