### ISSUE TITLE
Disabled days could still be highlighted

### ISSUE THREAD

**Issue by omitobi** [dangrossman/bootstrap-daterangepicker#1465]
I successfully was able to disable some days following:

https://github.com/dangrossman/bootstrap-daterangepicker/issues/835#issuecomment-148880120

One interesting thing I have not been able to successfully do that would be nice is to still highlight the days disabled when they cross the start date and end date after selection.

Here is how it is now:
![image](https://cloud.githubusercontent.com/assets/16482234/25662655/f510eb96-301d-11e7-9b8f-2bf38d934d86.png)

After observing the behaviour I discovered that if I manually remove the class 'off' from the disabled days then it appears highlighted too, while it is still disabled, so maybe having something like this:

![image](https://cloud.githubusercontent.com/assets/16482234/25662681/089beea4-301e-11e7-850f-bd67fe929bbf.png)

Although this is a nice to have feature at least specific, but Incase there is this possibility but not documented, I will be glad to see it.
Thanks.

**Comment by dangrossman** [comment]
I think the ability to disable days is mostly used with the single date picker rather than the date range picker, since what people would want to happen with date ranges crossing disabled days is ambiguous (there's probably multiple right answers depending on what the calendar is being used for). I can't really make any changes to how this works without breaking someone's site.
