### ISSUE TITLE
bug : during a range select, changing the month cancel the start date

### ISSUE THREAD

**Issue by soleromel** [dangrossman/bootstrap-daterangepicker#1519]
Hi,

here the cinematic to reproduce the bug : 
1/ click on a start date 
2/ click the right calendar input (name="daterangepicker_end")
3/ then click on the month changing arrows
will cancel the range selection process and highlight the left calendar input.

How can we fix that?

thx a lot.

**Comment by dangrossman** [comment]
I don't consider this a bug. Even if you disagree, it's not one that can be fixed, because the fix would involve reading human minds, which is currently impossible.

When you clicked on the right calendar input, it is expected you are now entering the end date of your range with your keyboard. 

When you exited the right calendar input, the end date of your range became the date that's typed in the input.

So your date selection is now over. You can click on month arrows or do whatever you want, you're now starting a new selection.

**Comment by soleromel** [comment]
Thanks for your response.

But can we consider that if this is the case we should check if the user has set the input date?

**Comment by dangrossman** [comment]
That is checked. You had a valid date in the text input when you left it.
