### ISSUE TITLE
Drop jQuery dependency?

### ISSUE THREAD

**Issue by gaui** [dangrossman/bootstrap-daterangepicker#1549]
Nowadays people are using less and less jQuery because it turns out it's unnecessary. People are wanting more and more framework-agnostic libraries, so they work with React/Angular/Vue/VanillaJS/etc, but to use this library you need to install jQuery. Everything however can be done without jQuery and it shouldn't have to be a dependency in a great library like this.

Please consider getting rid of jQuery as a dependency.

**Comment by dangrossman** [comment]
Feel free to make a non-jQuery fork. I will not be rewriting this one to remove jQuery. Not something I'm interested in doing at all.

**Comment by gaui** [comment]
Ok, but may I ask why?

**Comment by dangrossman** [comment]
Why would I want to re-implement jQuery's event handlers, selector API, DOM manipulation API, variable context wrappers, polyfills, etc to remove a dependency? Does that sound fun to you? It doesn't sound fun to me. Those things made writing this library possible in the first place. I am not going to invest the days or weeks it'd take me to reimplement half of jQuery to remove jQuery when literally nobody else has ever asked me to in the 5 years since I wrote this code.

**Comment by gaui** [comment]
Ok, fair enough. 😃

**Comment by trendoid** [comment]
Did anyone fork this for no jquery dependency yet?

**Comment by gpetrov** [comment]
@dangrossman - please reconsider dropping jQuery as dependence. You really don't have to re-implement all the jQuery stuff because modern browsers already support everything and jQuery is becoming more of an unnecessary load that only slows down your page.

**Comment by arpitprod** [comment]
I found [this](https://www.npmjs.com/package/react-advanced-datetimerange-picker) plugin for react based on this daterangepicker.
