### ISSUE TITLE
Ranges labels order

### ISSUE THREAD

**Issue by luca159** [dangrossman/bootstrap-daterangepicker#1569]
Simple problem: in my code (left) i define ranges in an order, but in the output (right) they appear in another.
Is it possible to keep the correct order?

![datarangepicker_range_prob](https://user-images.githubusercontent.com/30238433/30581243-c2ea1722-9d1f-11e7-9de9-e970f2f51d2c.jpg)

**Comment by theJoi** [comment]
Ditto. I'm also interested in being able to change the order of the labels instead of it always being in alphabetical order.

**Comment by dangrossman** [comment]
I've never seen it appear in alphabetical order instead of the order in which the ranges were defined. They appear in the order they were defined in Internet Explorer, Firefox, Chrome at http://www.daterangepicker.com/#ex4

**Comment by theJoi** [comment]
Sorry, you're right it's not alphabetical, however it is definitely not the same order I'm entering the ranges. This is what I'm seeing:
![screen shot 2017-10-17 at 11 07 52 am](https://user-images.githubusercontent.com/1295347/31675948-b80c920e-b32b-11e7-8267-b343131ff800.png)

My range code is the following:

       ranges: {
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
           '2017': [moment().startOf('year'), moment()],
           '2016': [moment().year(2016).startOf('year'), moment().year(2016).endOf('year')],
           '2015': [moment().year(2015).startOf('year'), moment().year(2015).endOf('year')],
           'ALL': [moment().year(2011).startOf('year'), moment()]
        }

**Comment by dangrossman** [comment]
Like I said, they appear in the order they were defined in every browser I have to test with. I don't have any further insight to share. You can rewrite the code to use an array instead of an object for this option if you'd like, I bet that'd fix it for whatever mystery platform you're using.

**Comment by arfordweb** [comment]
This is probably happening because object fields are not ordered.  Items being read from an object in the same order they were put into it is depend on the implementation details of the JS interpreter.  Any JS interpreter could write a different Object implementation that adheres to standards and does not result in fields of an object being read in the same order they were declared or added.

https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

The `fields` property should be an Array, despite the behaviors of existing JS environments.  Can the API be changed to accept either an Object or Array.  That would be backwards-compatible, but would guarantee the order of ranges is preserved.
