### ISSUE TITLE
Non-linked calendars and date selection

### ISSUE THREAD

**Issue by vipera** [dangrossman/bootstrap-daterangepicker#1605]
Hi,

When the linkedCalendars option is disabled, you get to navigate two calendars at a time. What would it take to have the date selection not toggle between start date / end date, but instead depend on the calendar in which you input it? So that clicking a date in the left calendar modifies the start date exclusively, and clicking the right one selects the end date?

I'd be happy to devote some time into developing this if you think it's a viable feature that might be merged upstream. Any guidelines are welcome too, if you have them.

Thanks

**Comment by dangrossman** [comment]
Here you go, it's already done for you: 

https://github.com/dangrossman/bootstrap-daterangepicker/releases/tag/v1.3.23

The behavior was changed because no other date range picker on a major hotel, flight, rental, analytics service worked like that, so it was novel and confusing to users. "First click is start date, second click is end date, on either side" is what people experience everywhere, but you can use the old version if you want the weird behavior.

**Comment by vipera** [comment]
Thanks Dan! Shame it wasn't kept in the later versions as an alternative option. I'm pretty much indifferent if it's one or the other, but my project stakeholders are firmly set on having the "weird" behaviour.
