### ISSUE TITLE
Selection changes when duplicate ranges are present

### ISSUE THREAD

**Issue by lohiarahul** [dangrossman/bootstrap-daterangepicker#1608]
I have the following ranges defined for my daterangepicker

![image](https://user-images.githubusercontent.com/2647136/32705566-c9501bbe-c869-11e7-8b0f-9cb10bd02f37.png)

On the 7th and the 30th of every month, the ranges 'Last 7 days' and the 'Last 30 days' have the same start and end dates as 'This month'. The daterangepicker works fine except that when the user selects 'This month' on the the 7th of any month, the selection changes to 'Last 7 days' as it occurs first in the list. I would like the control to retain the selection as it is slightly confusing.

**Comment by jason-klein** [comment]
We encountered the same issue, where the user cannot select certain ranges if they have the same date as another defined range (e.g. MTD/QTD/YTD). I've revisited this same issue several times and have not come up with a good solution. I am sharing our workaround here since I keep landing on this issue each time I research this. Hopefully others find this helpful!

Problem Description: When MTD and QTD and YTD have the exact same date range (e.g. 01/01-01/29), user cannot select the second or third defined range (e.g. QTD or YTD). If a user attempts to select the second or third range, the first range with the matching begin/end date is selected.

Workaround: We defined date ranges with actual ending date of the month/quarter/year (e.g. Month to Date 01/01-01/31, Quarter to Date 01/01-03/31, Year to Date 01/01-12/31) so that the date ranges do not conflict. We then updated our internal system to convert the full date ranges to the intended date ranges. For example, we define MTD/QTD/YTD date ranges for historical reporting. We only need to generate historical reports through prior day, so we automatically trim the date range ending dates to prior day (e.g. YTD 01/01-12/31 may be converted to internal YTD 01/01-01/29, where 01/29 is prior day).

This appears to be duplicate of [issue 621](https://github.com/dangrossman/daterangepicker/issues/621) and [pull 371](https://github.com/dangrossman/daterangepicker/pull/371).
