### ISSUE TITLE
Usage of locale leads to display of wrong year in calendar table

### ISSUE THREAD

**Issue by siliconwaldeck** [dangrossman/bootstrap-daterangepicker#1614]
Hi everyone,

the locale object on initialization of the daterangepicker looks like this
`locale: {
                format: 'dd DD.MM',
                daysOfWeek: startDateMoment.localeData().weekdaysMin(),
                monthNames:  startDateMoment.localeData().months()
            }`

It gives the output 'Sun 24.12 - Mon 24.12' in the daterangepicker input field but it also leads to display of the current year in the calendar table head instead of the specified one.

When changing the format attribute to something like 'DD.MM.YYYY' it is working fine (see examples in attachements).

In my opinion the binding of the locale object should no affect the display of the date in the calendar table head.

<img width="253" alt="daterangepicker_1" src="https://user-images.githubusercontent.com/20425940/33264527-3bdfb900-d36e-11e7-9676-35fc786271d1.png">
<img width="230" alt="daterangepicker_2" src="https://user-images.githubusercontent.com/20425940/33264528-3bfb54e4-d36e-11e7-8940-7244169990cc.png">

**Comment by dangrossman** [comment]
The problem is that you have a text input, which people can type in, so what's in there needs to be parsed... but since you aren't including a year in your date format, there's no way to know what year they want used when it gets parsed. So apparently `moment` assumes the current year. The fix is to include the year in your format string, or to not attach the picker to a text input. Attach it to a div or something.
