### ISSUE TITLE
Using arrows without selecting end date first

### ISSUE THREAD

**Issue by josefinscreentek** [dangrossman/bootstrap-daterangepicker#1628]
Hi,
We are facing a problem for our customers when using the range datepicker and they need to use the arrows to switch month/year.

If you first click on a start date (without dragging it to an end date), then, even if you select the end date box and then use the arrows to select the end date, the startdate is updated.

So the only way to create a date range that goes over several months/years, is to select a startdate and drag to a random end date, and after that you can use the arrows or dropdown to select a new end date.

There needs to be a more user-friendly way to select a date range over several months/years, that doesn't inlcude to select a "temporary" end date and then click to select a new end date.

I hope you can understand what I mean.

The best way would be if it was possible to click in the left range datepicker for start date. Then without dragging, the end date textbox is automatically focused and when you then click on a new date, even if you have switched month, (preferebly in the right range datepicker), then it automatically chooses that date as end date.

Thank you

**Comment by dangrossman** [comment]
Click a start date, click the right arrow as many times as you want, click a date, you've selected an end date. There is no "drag to random" requirement/problem.

Where you went wrong is clicking on the end date input, then clicking on the arrow, then clicking on a date and expecting to be picking an end date. When you clicked into the end date input, it is expected you did so to change it -- by typing something -- otherwise why would you have clicked there? When you clicked outside of the input, whatever you typed there is taken as the end date, so you have completed your selection. Now you go and click on a different date in the calendar, you're starting a new selection, not changing the end date of the existing selection.

**Comment by josefinscreentek** [comment]
I will try to forward that explanation to our customers, that's using the datepicker in our solution. Because somewhere in the line, several of them has reported the datepicker not working as expected anymore (we previously used an much older version of the plugin), so something with the logic must have changed. Although, I tried your explanation in our environment and that works.

I think the reason is that if you have a daterange already pre-selected (as we usually have), and then click in the right datepicker, it starts over with a new range, and that's confusing them.

I think it would be more user-friendly, when you do have two datepickers in a range, that when selecting a date in the right datepicker, that's always the end date, and when selecting a date in the left datepicker, then it's always the start date.
What other reason is there to have two datepickers for the range if that's not make any difference according to that? Then it would be better with the "single datepicker" layout, with one datepicker, but the same logic behind it.

**Comment by dangrossman** [comment]
Try finding a date range picker in the wild that works like that, because all the ones I can find have two calendars, and whether you're picking the start/end of the range is determined by the order of the clicks, not by what calendar you use. Also, if you prefer how an older version worked, I suggest you stay on it. This isn't an operating system or something, it's a bit of javascript to show some calendars, there's no need to be on the "latest version" or anything.
