### ISSUE TITLE
From to To date issue

### ISSUE THREAD

**Issue by vishalsingh119** [dangrossman/bootstrap-daterangepicker#1632]
Hi,

Last time you make a fiddle for some other issue.
Fiddle - https://jsfiddle.net/8auw2rcp/4/

Now the issue is when we click on the apply button then start date in ''from' effect 'to' date. 
But the issue will occur when the user directly clicks outside of date picker.we tried all jquery event like mouseleave, blur etc but it's not working. plz, give us some solutions.

Thanks

**Comment by dangrossman** [comment]
There is no apply button to click on in that page.

I suggest you hire a developer or post a full demo of your problem on Stack Overflow.

**Comment by vishalsingh119** [comment]
Thank you for the suggestion, soon I will do that.

https://jsfiddle.net/vishalsingh119/8auw2rcp/8/

just check that fiddle, in previous one i forget to add time picker. when we add time picker then only apply btn will come. So i am expecting without clicking on apply btn its should work. I tried autoApply also, but it's not working.

**Comment by dangrossman** [comment]
Your new fiddle doesn't contain the code I gave you, or any other code that makes one picker affect the other in any way. I don't understand your description of the problem, and it doesn't match what happens when clicking dates or buttons in that fiddle. Hire a developer, explain to them clearly what you want to happen. Please don't open any issues on this repository unless you're reporting a bug.
