### ISSUE TITLE
autoApply and timePicker do not work together

### ISSUE THREAD

**Issue by TheZoker** [dangrossman/bootstrap-daterangepicker#1643]
When the `timePicker` is true, the `autoApply` does not work anymore.

Why is that?

**Comment by dangrossman** [comment]
Because it would require mind reading to know when the user has finished their date and time selection to "auto apply" it

There is no UI event that signifies completion, like clicking a date when there is no time picker

**Comment by TheZoker** [comment]
You can update it as soon as the user selects anything from the dropdown or any date.
The only thing I want is, that the value in the input field gets updated as soon as the user changes anything and he does not need to hit an apply button.

**Comment by dangrossman** [comment]
You will have to code that yourself as this library does not have that feature

"Applying" the selection means closing the picker, updating the input, triggering your callback function and triggering several events. We can't "auto apply" the selection as soon as anything changes because they won't be able to finish the selection (e.g. they've selected only the hours and we take away the UI before they have a chance to choose the minutes).

**Comment by TheZoker** [comment]
Hmm I see your point. What about an auto Update option, that just updates the input field without closing the picker?
