### ISSUE TITLE
Apply/Cancel buttons are visible when using custom ranges although autoApply is set to true

### ISSUE THREAD

**Issue by lgespee** [dangrossman/bootstrap-daterangepicker#1653]
When setting the `autoApply` options to true, makes the apply and cancel button disappear, as expected.
Once custom ranges are added using the `ranges` option, the `autoApply` option settings seems to be ignored.

Is this behavior by design? Wouldn't it rather be more logical to have `autoApply` hide the buttons, no matter if custom ranges are used?

**Comment by dangrossman** [comment]
Head over here: http://www.daterangepicker.com/#config

Check off "autoApply" and "ranges".

The picker has no apply or cancel buttons.

I'm guessing you have the time picker enabled, which needs an apply button, because you can't know when the user has finished their selection (may take up to 10 clicks in any order!) of two dates and times otherwise.

**Comment by lgespee** [comment]
Thanks for your fast response, your reply made me look into the example of the configuration generator and I found the cause of the issue. Using Bootstrap 4 causes the buttons to appear.

Are there any plans for supporting Bootstrap 4?

**Comment by gblachonupg** [comment]
Added this to my scss : 

`.daterangepicker {
  .applyBtn 
  {
    display: none;
  }
  
  .cancelBtn 
  {
    display: none;
  }
}
`
