### ISSUE TITLE
Add composer and components?

### ISSUE THREAD

**Issue by gintsmurans** [dangrossman/bootstrap-daterangepicker#543]
I could make a pull request for this if nobody is against it.

**Comment by dangrossman** [comment]
Could you add some ham sandwich? I'm a bit hungry. On a related note, I don't know what "add composer and components" means here. :/

**Comment by gintsmurans** [comment]
Oh, sorry, I mean this thing: https://getcomposer.org/ - its a php package manager similar to bower. And by components I meant to add dependency on robloach/component-installer. Here is a composer.json example file from moment.js: https://github.com/moment/moment/blob/develop/composer.json.

**Comment by ThaDafinser** [comment]
@gintsmurans since i come from the php world....please do *NOT add composer support!*
https://getcomposer.org/ -> dependency manager for *PHP* and NOT javascript.

You will be able to install it then with composer -> but what about version conflicts in your different JS libs?

**Comment by gintsmurans** [comment]
@ThaDafinser I am not sure I follow. By conflicting libs, do you mean that, for example, different version of bootstrap won't work with the latest version of daterangepicker? You can easily specify in composer.json which versions it should download. Also, it is a php package manager, but that doesn't mean it can't have javascript libraries. A lot of existing javascript libraries is already on packagist.org, ironically, bootstrap is one of them - https://packagist.org/packages/twbs/bootstrap. :)

**Comment by ThaDafinser** [comment]
@gintsmurans only because many people do something, it doesnt mean that its the right way to do something :smile: 

### Lets take your boostrap example
It's on packagist right, but where is the required jquery version defined? https://packagist.org/packages/twbs/bootstrap

Right it's not defined...but in bower.json it is https://github.com/twbs/bootstrap/blob/master/bower.json#L37

The javascript developer will never care about a php package manager and even if it would be defined in composer.json it will be nearly always wrong, since they wont update that package definition.

I hope you see what's the problem....but maybe there is already a composer package, which can use bower.json to install it with php?
http://bowerphp.org/
https://github.com/francoispluchino/composer-asset-plugin

**Comment by gintsmurans** [comment]
hmm, ok, jquery is not there, but something else won't be on, for example, bower. I mean that is not a reason not to put daterangepicker on composer. Maybe javascript developer never cares about php, but there are php developers who does php and javascript. In fact, if project is php, then most probably there will also be html, css and javascript. I, for example, very much like to stick with one package manager and avoid using different manager for each library. If its a php project, lets use composer for all libraries and assets, if its node, lets use npm. Thats why libraries like daterangepicker should be available on all major packaging/dependency managers.

Only reason not to put library on package manager should be something technical, like, manager's directory structure is no good for the library, which makes the library unusable.

Most probably we are seeing this from different angles. I am using daterangepicker on my php projects, logically I would like to see it on composer as I am using composer. Would it hurt anyone if daterangepicker would be on packagist? I think daterangepicker would only gain from that, because it would be another way to use the lib.

**Comment by ThaDafinser** [comment]
@gintsmurans i think you didnt got me.

> Maybe javascript developer never cares about php, but there are php developers who does php and javascript.

I'm also a main PHP developer which using a lot of js and css libs....
I would also like to use only one package manager, but that will not work (correctly) in the near future.

> Only reason not to put library on package manager should be something technical, like, manager's directory structure is no good for the library, which makes the library unusable.

Technical you can do that (never said something else), but
- not all JS/CSS packages are currently on composer (so if you have a dep on such a package you are stuck)
- Not all JS/CSS packages on composer do have semantic versioning and/or declared their dependencies correctly
- the composer.json will (likely) not be updated by JS developers

`The main benefit from a package manager, is not the downloading of a package, but it's the dependency and version resolving and you will lose that partly that way.`
Not because composer cant handle it, but because the composer.json metadata are not maintained

Anyway: Feel free to do it that way, but i can sleep now well, since i warned you enough :smile:

**Comment by ThaDafinser** [comment]
A side note:
When i started using bower i hated it. But with all the awesome tools like gruntJS you will not use anything else anymore ;-)

**Comment by gintsmurans** [comment]
> not all JS/CSS packages are currently on composer (so if you have a dep on such a package you are stuck)

And they won't be with this attitude. :) Most probably there are libraries that are not available to bower, too, so with this reasoning we shouldn't add bower.json to new libraries, because not ALL packages are available to bower (possibly because they are not using semantic versioning).

> Not all JS/CSS packages on composer do have semantic versioning and/or declared their dependencies correctly

Thats fine. For example, composer doesn't specify any dependecy at all, but as a developer, i know it needs jquery. So I go and find jquery, which in this case is here- https://packagist.org/packages/components/jquery.

**Speaking of correct dependecies - daterangepicker doesn't have bootstrap defined as a dependency in bower.json.** :)

> the composer.json will (likely) not be updated by JS developers

Why not? Its not like composer.json is written in php or something. Its just a json file, just like bower.json. If you want to add dependecy on jquery in bower.json, you still have to find out the exact name of the package, what versions are available, etc, same as composer.

**Comment by MaikuMori** [comment]
There shouldn't even be a discussion. *Use dependency manager provided by each language and supported by their community.*

For nodejs/server-side-js it's npm
For frontend assets/js it's bower
For Python it's pip
For x it's y

There is no such thing as universal dependency manager, it's a hard problem to solve. Each language/environment has specific things that you must think about when you develop a dependency manager.

Asking frontend javascript tool to support a php dependency manager is as absurd as to ask it to add pip support, haskel dep manager support or maybe crate support because there is that one guy who uses this project with his rust program. Why should somebody who cares only about fronted support all 50+ commonly used dependency managers?

Use the right tools for the job. Don't hammer a screw just because you can with enough force.

**Comment by gintsmurans** [comment]
All these comments about reasons not to use composer because of composer not having semantic versioning, or because javascript libraries doesn't belong to php package manager, or "Don't hammer a screw just because you can with enough force" :D are pointless. @MaikuMori Look around at bower, npm, composer, and other manager's repositories, there are packages available on all of them that "shouldn't" be there. Even pip have some ways to install javascript libs. And composer have tons of javascript libraries. Because people find it very easy to install javascript libs using the same dependency manager they are already using, they put them up there, so they don't have to install node stack just to get one js library.

Anyway, I really have no interest in going further with these arguments, if daterangepicker developers don't want composer support, fine, I can download it manually.

**Comment by ThaDafinser** [comment]
> Look around at bower, npm, composer, and other manager's repositories, there are packages available on all of them that "shouldn't" be there. Even pip have some ways to install javascript libs. And composer have tons of javascript libraries. Because people find it very easy to install javascript libs using the same dependency manager they are already using, they put them up there, so they don't have to install node stack just to get one js library.

Like i said early: Only because many people do something, it does not mean that it's the right thing to do something....

> Anyway, I really have no interest in going further with these arguments, if daterangepicker developers don't want composer support, fine, I can download it manually.

@gintsmurans issues are here to discuss. The benefit of it is that you normally learn something or can take with you - if you are willing to (I had to learn that also some time ago....)

Anyway - please dont take anything personal. If you think composer is the right way to go for you - ask @dangrossman if he wants to merge a PR including the composer.json from you?

Since me and @MaikuMori are more users then developers of daterangepicker

**Comment by dangrossman** [comment]
I don't want to collect config files for every language's package manager. Thanks.
