### ISSUE TITLE
Different jQuery-requirements

### ISSUE THREAD

**Issue by marcovtwout** [dangrossman/bootstrap-daterangepicker#547]
Why is the jQuery-requirement in packages.json `^2.1.1`, while in bower.json it's `>=1.10`?

**Comment by MaikuMori** [comment]
@kopax wanted npm package, which is why we have `package.json` now, but nobody really maintains it. 

I believe there isn't a real dependency on jQuery 2.x in the code (needs verification). Feel free to make a quick PR and fix it.

*Peronally I like to manage nodejs backend packages with npm and frontend package with bower and therefore we shouldn't even have `package.json` here as this is clearly a frontend library. But different people have different needs and opinions.*

**Comment by kopax** [comment]
I was also using bower for mainting frontend library.
Now I use browserify, (write client side like in node), browserify require is library in node_modules directory.
We have tried dangrossman for a year with jQuery 1.10, before browserify and it worked perfectly.

jQuery 2.0 and jQuery 1.10 are the same except the size, jQuery 1.10 has like half of his lines of code for fixing old browser compatibility issues.

Note that It work like a charm with jQuery 2.0 and 1.10, if the version is different, it is because I didn't check the jQuery version used in bower.json when I was doing the node package.

Please do not remove jquery dependencies in package.json.

daterangepicker.js will do a require('jquery') 
browserify will look in node_modules for jquery.

Feel free to change the package.json with jquery >=1.10
