### ISSUE TITLE
Event trigger order + dismissing

### ISSUE THREAD

**Issue by Hrafnkellos** [dangrossman/bootstrap-daterangepicker#596]
When clicking the apply button, the hide event is fired before the apply event. Shouldn't it apply first, then hide?

    this.hide();
    this.element.trigger('apply.daterangepicker', this);

Also when dismissing (clicking outside) the daterangepicker, shouldn't it fire the cancel event?

**Comment by dangrossman** [comment]
"Shouldn't it apply first, then hide?"

I'm no philosopher. Do you have a use case where it matters?

"Also when dismissing (clicking outside) the daterangepicker, shouldn't it fire the cancel event?"

No. `cancel.daterangepicker: Triggered when the cancel button is clicked`

**Comment by Hrafnkellos** [comment]
i have a radio button which i want to revert if no date is selected. but if the apply buttons is clicked i don't want to revert the radio button.

so if daterange picker is dissmissed(hiden). i revert the button.

then the radio button value is reverted before the apply event is fired.

i want to send the un-reverted value with the date range button apply click.

**Comment by cyuseff** [comment]
If you use both events, "hide.daterangepicker" and "apply.daterangepicker", only hide will be triggered because is calling first.

**Comment by marek-maciejewski** [comment]
Sorry for digging this up...
Here's my use case:
I use the daterangepicker in an inline edit that gets created dynamically after clicking onto a date text in a table. The user clicks cancel or apply to set the date, but I would also want to just revert the entry if the user simply clicks away outside the date picker.
For this I handle my revert/cancel routine in the hide event as well.
But in this case, when a user wants to apply a date, hide gets called first and reverts.
I did not find any information in the hide event itself that could help me determine if the hide is happening because of pressing apply, cancel or if it is by clicking outside the datepicker so I could stop/control the execution.

If I do touch the hide event and let the user click away, it leaves the inline edits open since they're unresolved... a tad ugly.
A hassle to code around that, if the daterangepicker could help out with in this case it would be very simple. :)
Or I could change order of calls in daterangepicker itself... can you advise if this change could break anything?
