### ISSUE TITLE
when input initial value is null,range is 'today-today', not call callback function 

### ISSUE THREAD

**Issue by gynantimdt** [dangrossman/bootstrap-daterangepicker#637]
![image](https://cloud.githubusercontent.com/assets/7029338/7389014/ce63a2d2-ee9c-11e4-933b-fcfc6dee10f7.png)

then click 'apply' callback function not  execution
![image](https://cloud.githubusercontent.com/assets/7029338/7389138/b6dd6642-ee9d-11e4-8292-6151ecc96c62.png)

because of
![image](https://cloud.githubusercontent.com/assets/7029338/7389095/6c39cbe4-ee9d-11e4-84b9-cc4d8da59b1b.png)

**Comment by DmLapin** [comment]
I confirm this problem. If input is empty, preset range `"Today" : ["moment().startOf('day')", "moment()"]` becomes unselectable. Moreover, it displayed as active but must not.

**Comment by dangrossman** [comment]
The date range picker always has a current startDate and endDate. If you don't provide them, they will default to "today". So yes, "Today" is already selected and opening/closing the picker without changing the selected date will not trigger your callback again. This is never going to change. Work with it. Either provide the initial startDate/endDate you want instead, or initialize your input box at the same time you attach the picker to it so that they reflect the same initial state.
