### ISSUE TITLE
Daylight savings issue reproduceable in examples

### ISSUE THREAD

**Issue by tb9-Mason** [dangrossman/bootstrap-daterangepicker#650]
There's a disparity between what's shown in the input box and what's shown in the date range picker when you are selecting a date during daylight savings time. I am in the Eastern time zone -4 GMT. Here's how to reproduce:  
* Go to [this example](http://www.daterangepicker.com/#ex2)
* In the input box, change the second date to 05/01/2015  

The daterangepicker now looks like this:
![screen shot 2015-05-12 at 1 56 40 pm](https://cloud.githubusercontent.com/assets/4603613/7594477/db5ca7d8-f8ae-11e4-86b7-397623b7f6cb.png)  

You can see that the hour in the select box is reduced by one hour. Changing the time in the input box will continue to set the time in the picker one hour off. When clicking apply, the time is set to the value in the select box.

**Comment by pleepleus88** [comment]
I think the issue is related to this line, in buildCalendar - 

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1012
`var curDate = moment([lastYear, lastMonth, startDay, 12, minute, second]).utcOffset(this.timeZone);`

It appears to utc-offset the actual dates referenced by the calendar, but I don't think they need it - all utc/timezone transformations seem to happen after the dates are applied.

When I remove the `.utcOffset(this.timeZone)` fragment, it seems like everything works correctly for me. 

Anyone have thoughts on whether removing this would cause other issues? Is it worth pull-requesting, or does it have obvious flaws?

**Comment by AshCoolman** [comment]
Cavaet: I don't much experience dealing with date/time edges cases

@pleepleus88  Nice, I poked your solution a bit and it held up. When tried reasoning the code a bit, I ended up with a change at https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1020 :

```
                calendar[row][col] = curDate.clone().local().hour(hour);
                                                    ^      ^
```

Would appreciate opinions, this seems like odd behavior :+1:
