### ISSUE TITLE
Suggestion: Option to step through months in dual mode

### ISSUE THREAD

**Issue by artknight** [dangrossman/bootstrap-daterangepicker#712]
I would like to see an option to have only two arrows at the top, and when clicked both months will change accordingly.

Please see screenshot for details.
![screen shot 2015-07-16 at 11 59 32 am](https://cloud.githubusercontent.com/assets/157762/8728347/9a56b7c4-2bb2-11e5-9ccf-70aecda85d9e.png)

**Comment by dangrossman** [comment]
If the date range you're selecting is more than a month apart, you would lose view of your selection between choosing the first and second date. I considered this and decided against it.

**Comment by artknight** [comment]
Would it be possible to have at least an option though? If absolutely not possible, would you please provide a possible custom solution that could be implemented by those who do desire it.

Thanks,

**Comment by dangrossman** [comment]
I don't really take feature requests. The issue tracker is for reporting bugs.

If you'd like custom functionality, you either have to develop it or hire a developer to do so for you.

**Comment by artknight** [comment]
I am developer, but I really hate to make changes to the core lib. It tends to create conflicts when trying to upgrade the core lib later on. If I were to develop a solution, would you be willing to merge it then?

**Comment by artknight** [comment]
BTW, if you look at any travel sites like expedia.com or kayak.com, etc... you will see that this is how their range picker works. They have done a ton of research on what customers want, so it would be nice if we had that option as well!

**Comment by dangrossman** [comment]
It would be nice if I had a million dollars.

**Comment by artknight** [comment]
This is your reply, seriously! ...lame dude!

**Comment by dangrossman** [comment]
I'm a person, Arthur. A person who you don't know, and who has no obligations to you. You've spent your day coming up to me and telling me about the work you'd like me to do. I've told you that I don't want your work requests. How "lame" would it be if I started e-mailing you throughout the day things like "it'd be nice if you could mow my lawn, my lawn isn't mowed" and "I wish my shirts were reversible, so I could wear them inside out for a different style, would you sew me a few reversible shirts?". As such, I'm going to block you from this issue tracker, so that I can get back to my job.
