### ISSUE TITLE
Typing End Date changes Start Date (2.0.7)

### ISSUE THREAD

**Issue by pherrmann** [dangrossman/bootstrap-daterangepicker#760]
Manually typing the End Date changes the Start Date. You can observe the behavior using the basic demo at http://www.daterangepicker.com/ 

The demo defaults to 01/01/2015 - 02/01/2015. I manually type 10/15/2015 in the End Date field and the Start Date changes to 10/15/0020

![image](https://cloud.githubusercontent.com/assets/11235473/9151225/d44e34c8-3dc0-11e5-9479-43936b9211d1.png)

**Comment by perrosen** [comment]
Yeah, saw this issue in all V2 releases. Had to roll back to latest V1 release.

**Comment by Shachar16290** [comment]
Same here.
Also when I press TAB after typing, it changes the dates.
Are you going to fix that soon?

**Comment by dangrossman** [comment]
In the process of typing "10/15/2015" you type "10/15/20" which is October 15th in the year 0020. The startDate can't be a later date than the endDate of the range, so it's moved to October 15th in the year 0020 as well.

See if you like v2.0.9 any better. It only updates the dates after you leave the text box, rather than as you type.
