### ISSUE TITLE
option function to disable dates

### ISSUE THREAD

**Issue by antonellopasella** [dangrossman/bootstrap-daterangepicker#835]
Is there any way to mask as "unselectable" some days? Or to apply custom class to particular dates?

**Comment by dangrossman** [comment]
Yes, that's the `isInvalidDate` setting. You provide a custom function that is passed each date in the calendar and returns true or false. 

http://www.daterangepicker.com/#options

**Comment by stephenkjohnston** [comment]
Can you provide an example? I would like to only enable weekdays and unfortunately there is no documentation on this that I could find :(

**Comment by dangrossman** [comment]
````javascript
isInvalidDate: function(date) {
  return (date.day() == 0 || date.day() == 6);
}
````

**Comment by stephenkjohnston** [comment]
One more question --- how can you detect the start of the month? I've tried date.day() === moment().startOf('month') but ti returns all '1's. Since date is a moment object I also tried date.startOf('month'). What's the best way to do this?

**Comment by dangrossman** [comment]
`day()` is day of week not date

`date()` is the date of month component of the object (1-31)

**Comment by stephenkjohnston** [comment]
Thanks. Is there a way that these examples could be added to the method documentation? Aslo, for any future person looking the below is to highlight the first day of the month.

```javascript
isInvalidDate: function( date ) {
 if( date.date() === 1 ) {
   return false; 
 } else {
   return true;
 }
}
```

**Comment by dangrossman** [comment]
Or more succintly, `return date.date() > 1`. I'll keep it in mind if I ever feel the inclination to add more examples.

**Comment by wgdains** [comment]
If anyone was looking to disable days before and after a certain date, here is the code. The reason I'm doing this, is I need to limit how much data I'm allowing to be queried due to Advantage Database network limitations.

First, I created 2 variables that will be used to hold the cut off dates. This can be achieved multiple ways, but would look something like this:

`$startcutoff = date("Y-m-d", strtotime('-31 day',strtotime($today)));
$endcutoff = date("Y-m-d", strtotime('31 day',strtotime($today)));`

Now that I have the start and end date, I assign them to my JavaScript variables, and I can use them in the below statement.

`if (date.format('YYYY-MM-DD') <= startcutoff || date.format('YYYY-MM-DD') >= endcutoff) {
              return true; 
            } else {
              return false;
            }`

Hope this helps someone!
