### ISSUE TITLE
styilng conflict when using zoom attribute in Google Chrome

### ISSUE THREAD

**Issue by HOuaghad** [dangrossman/bootstrap-daterangepicker#837]
Hi,

After having specificed the zoom attribute to 90% while using google chrome, the calendar opens quite many pixels away from the input I have specified it to...

![untitled](https://cloud.githubusercontent.com/assets/13497307/10524830/87c23520-7379-11e5-90b1-015e94943b2f.png)

**Comment by dangrossman** [comment]
What is the "zoom attribute"? I see no such problem when zooming the whole page (using the menu or ctrl and +/-) in Chrome.

**Comment by HOuaghad** [comment]
css zoom attribute..

**Comment by dangrossman** [comment]
"The zoom property in CSS allows you to scale your content. It is non-standard, and was originally implemented only in Internet Explorer. Although several other browsers now support zoom, it isn't recommended for production sites."

I must concur, and will not be investing any of my own time into researching this.

**Comment by JoshuaVB** [comment]
@jshrt it's been a very long time since you asked this, but your request was the only Google result I ended up getting on this issue. My client was demanding initial zoom via CSS on page load for his application, and it was breaking the daterangepicker.

For anyone else who may come along this via Google, here is the solution that worked for me (although it is hacky). My initial zoom was requested at 67%, so here's the javascript that solved the issue for that zoom level:

`var reshown = false;
datepicker.on('show.daterangepicker', function(ev, picker){
		if (!reshown) {
			$('html').css('zoom','100%');
			reshown = true;
			$(this).trigger('click');
			$('html').css('zoom','67%');
		} 
		else {
			reshown = false;
		}
	});
	datepicker.on('showCalendar.daterangepicker',function(ev,picker){
		$(this).data('daterangepicker').hide();
		$(this).data('daterangepicker').show();
	});`

The trick here is that the daterangepicker works fine when the initial zoom is 100%, and then it is scaled back down. It just can't be that zoom level initially. So we set the html zoom level to 100%, re-open the datepicker, and then set the zoom level back to 67% which it was originally. 

In the original questions' example it would be 90%.
