### ISSUE TITLE
Input won't be updated on time range "today" if selected first

### ISSUE THREAD

**Issue by BlueBeN82** [dangrossman/bootstrap-daterangepicker#866]
In your example "Predefined Ranges" at http://www.daterangepicker.com seems to be a bug.
When i open the picker in the demo and choose "Today" as my very first choice, the date in the span won't get updated. If i choose "Yesterday" first and "Today" after that everything works as expected.

**Comment by dangrossman** [comment]
It's not a bug so much as an omission: in the example, I didn't set an initial start/end date, so they are set to the default, which is the current date. "Today" is already chosen, clicking it again won't execute the callback that updates the span because the callback is only executed when the chosen date(s) change.
