### ISSUE TITLE
Calendars get "stuck" on mobile (can't scroll past the first one)

### ISSUE THREAD

**Issue by sitelifters** [dangrossman/bootstrap-daterangepicker#884]
On mobile, when I select the date range picker element, the calendars get stacked correctly, but I can't seem to scroll down past the first calendar to see the next calendar and the prefilled ranges no matter what I try. Any ideas?

![screen shot 2015-11-30 at 4 20 55 pm](https://cloud.githubusercontent.com/assets/3444539/11484867/7b3b8a30-977e-11e5-90d7-62305b8a5c38.png)

**Comment by dangrossman** [comment]
No ideas. I think this is something specific to the rest of the HTML/CSS in your page, because I can scroll on a page that has just Bootstrap and the date range picker.

![screenshot_20151130-164803](https://cloud.githubusercontent.com/assets/407706/11485623/3e7524f4-9782-11e5-8a59-d1408dd3f531.png)

**Comment by Techn1x** [comment]
Sorry to necro a closed issue @dangrossman , but I'm having a similar issue, and hopefully can shed some light for anyone else who might be experiencing this.

For me, it seems to be because I placed the daterangepicker input/button (what the calendar should be anchored to) inside a scroll element on the page, whereas the actual calendar is absolutely positioned on the page (in the body element), rather than inside the scroll element. So when I scroll the calendar nothing happens, when and I scroll the page behind it, the element scrolls and the calendar stays put without moving.

Playing around with the html/css in chrome's inspector, if I move the daterangepicker div to be inside the scroll element, and set position:relative on the scroll element, this fixes the issue (the calendar & scroll element scroll together), however then the absolute position's are out because they're based on the body element.

Do you know the best way to place the daterangepicker div inside where I need it in my app, and to also set the absolute positions based on the element it is inside?

Or given this info and your far better knowledge of how the daterangepicker works, do you know a better way to fix the issue I'm having?

Thanks

**Comment by dangrossman** [comment]
> Do you know the best way to place the daterangepicker div inside where I need it in my app

The `parentEl` option (default 'body')

**Comment by Techn1x** [comment]
Thanks! Fixed everything. Couldn't see the simple solution that was right in front of me :)
