### ISSUE TITLE
Moment.js v2.11.0 - deprecation (construction using a non-iso string is deprecated)

### ISSUE THREAD

**Issue by bricss** [dangrossman/bootstrap-daterangepicker#912]
Hi there,

After the upgrade to the new version of moment.js started getting that messages in console:
> Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

**Comment by swarthy** [comment]
+1 :thumbsup:

**Comment by dangrossman** [comment]
I don't see anywhere in the code where a moment object is constructed from a string without a format string.

**Comment by KirillMehtiev** [comment]
Hi,
Same thing, it happens when I turn on time for picker `{timePicker: true}` . I use picker v2.1.18 and moment v2.11.2, also I use this [directive](https://github.com/fragaria/angular-daterangepicker).  Any ideas what it can be?
![prof](https://cloud.githubusercontent.com/assets/10028598/13573167/f7639364-e486-11e5-9034-da4efdbf2189.png)
Thanks in advance!

**Comment by will-tr** [comment]
+1, I get this warning with latest moment and v2.1.19 when timePicker: true

**Comment by micheleva** [comment]
+1 I get it with timePicker: true

**Comment by keybrdist** [comment]
for those still asking about this.. see #1010
