### ISSUE TITLE
daterange picker time not select

### ISSUE THREAD

**Issue by enginhazar** [dangrossman/bootstrap-daterangepicker#923]
I've using Moment.js adminlte

region 'tr' turkey range picker time not selection open
 

![image](https://cloud.githubusercontent.com/assets/1329708/12249415/40956200-b8c8-11e5-8bcf-d63e273e2f61.png)

    $('#izlemeAralik').daterangepicker({
        timePicker: true, timePicker24Hour: true, timePickerIncrement: 30, format: 'DD/MM/YYYY h:mm',
        autoApply: true,
        dateLimit: {
            days: 7
        }
    , locale: {
        applyLabel: 'Tamam',
        cancelLabel: 'Vazgeç',
        fromLabel: "Başlangıç",
        toLabel: "Bitiş",
        daysOfWeek: [
                "Paz",
                "Pzt",
                "Sal",
                "Çar",
                "Per",
                "Cum",
                "Cts"
        ],
        monthNames: [
                "Ocak",
                "Şubat",
                "Mart",
                "Nisan",
                "Mayıs",
                "Haziran",
                "Temmuz",
                "Ağustos",
                "Eylül",
                "Ekim",
                "Kasım",
                "Aralık"
        ],
        firstDay: 1
    }
 
    });

**Comment by dangrossman** [comment]
Based on your screenshot, you are using a version of this library that's at least 22 releases old. It's possible there was a bug in that version, and also possible it was fixed in any of the subsequent 21 versions. 

I would start by updating your code to the latest version. When you do so, the `format` option became part of the `locale` object (like `daysOfWeek`) 6-7 months ago, so you'll have to change your options a little.

If you think you've discovered a bug in the latest version of this library, feel free to open a new issue about that.
