### ISSUE TITLE
Cannot open the datepicker with javascript

### ISSUE THREAD

**Issue by AlexCppns** [dangrossman/bootstrap-daterangepicker#951]
I tried:
```
$("#daterange-picker").show();
$("#daterange-picker").data().daterangepicker.show();
...
```

**Comment by dangrossman** [comment]
`$('#daterange-picker')` is the element of your page you've attached the picker to, not the picker. 

`$('#daterange-picker').click();` would trigger opening the picker, since it opens when the thing you attached it to is clicked on.

`$('#daterange-picker').data('daterangepicker').show();` would be the correct way of getting at the picker object and showing it directly.

**Comment by AlexCppns** [comment]
I found the problem, it was the event propagation that messed things up.
