### ISSUE TITLE
Entering 2 Digit Year on a 4 Digit Required Year Results in a Bad Year

### ISSUE THREAD

**Issue by Ripsnorta** [dangrossman/bootstrap-daterangepicker#955]
When using the date range picker with the following setup

`$('#{id}').daterangepicker({locale: {format: 'DD/MM/YYYY'}, singleDatePicker: true, showDropdowns: true});`

and the user enters a date with a 2 digit year, for example: 04/02/16 the user will get a date formatted as 04/02/0016 displayed in the edit box.

Now I've hacked the code in one of the update functions to check if the year is less than 100 and if it is to add 2000 to it and that works if I just change the date in the edit field. But if I enter the 2 digit year in the edit box and then click on the calendar to complete the action the resulting year will again be displayed as 0016. I haven't yet found where this is happening.

I won't attach the changes here because while the hack suits my purposes it's probably not what you are going for.

**Comment by dangrossman** [comment]
1. Go to http://www.daterangepicker.com/#config

2. Check off "singleDatePicker"

3. Check off "showDropdowns"

4. Enter "04/02/16" into the box

Result: The year does not change to 0016. 

In the more general sense, maybe you want to attach your calendar to a button or a disabled input, so that users can't type bad values into your form in the first place.
