### ISSUE TITLE
Predefined date ranges doesn't update/re-evaluate time when applied

### ISSUE THREAD

**Issue by MaxOrelus** [dangrossman/bootstrap-daterangepicker#966]
I'm currently using the predefined dates but I have them with low increments.

* 5 minutes
* 15 minutes
* 30 minutes
* 1 hour

When initialized the first time these predefined ranges work because I just initialized them with the daterangepicker. If I wait 5-10 minutes later and I re-select a predefined time frame, it doesn't re-evaluate the time, it put's the time it calculated 10 - 15 mins ago. This bug would have the same effect if a person used the default day increments shown with the demo. If a person loaded a page yesterday and selected today, yesterday's date would still be shown instead of today.

```js
"ranges": {
	"5 Minutes": [
	moment.utc().subtract(5, 'minutes'),
	moment.utc()
        ]
}
```

**Comment by dangrossman** [comment]
Lacking a feature you want is not a bug. The date range picker never evaluates anything, it's taking date objects passed to its constructor, and date objects don't change themselves. They already existed when you made them, before the date range picker was made and handed their values.

Anyway, to the practical solution. Compute the ranges you want in your callback function, at the time a selection has been made, so that they're relative to that time.

```
$('#yourelement').daterangepicker({
  ranges:  { //your ranges }
}, function(start, end, label) {
  if (label == '5 Minutes') {
    start = moment().subtract(5, 'minutes');
    end = moment();
  } else if (label == '10 Minutes') {
  ...
}
```

**Comment by TCOA** [comment]
> the immediate practical solution

doesn't really work...... :(

1. It doesn't update the picker dates (when using .on('apply.daterangepicker' function, the 'old' dates still show.....)

2.  for the times to update (i.e., you have clicked on a button once, you wait, then want to update the time - as explained in the OP), you have to click some OTHER button first, then back to the one you want before the 'new' times will actually change.

Even though you can use the updated info in your code to get the correct data, the UX is quite bad since the user doesn't see the change (and having to tell them to 'click something else first'....)

Is there something more to this 'practical solution' that can be done to actually make a good UX???

BTW, for anyone reading this update - anything in the "ranges: {}" other than labels are a waste of time to put in as they get overwritten (a pretty important bit of info I would liked to have had before!......)

Hopefully there is a more elegant (and useful) solution to this?
