### ISSUE TITLE
SingleDatePicker don´t set current date

### ISSUE THREAD

**Issue by ramilani12** [dangrossman/bootstrap-daterangepicker#969]
Hi
I have  faced an issue with date picker with config: SingleDatePicker and autoUpdateInput.
I want my input empty value when the user access my page then I use autoUpdateInput : false, It works!
But when I click an input and try to select the current date for example today the datepicker don´t set the value, but with diferent value from today it works.

I´ve tried a lot to fix that, but in vain.

**Comment by dangrossman** [comment]
I assume you're populating your input in a callback function. Callback functions are only triggered when the selected date changes. If you haven't set a `startDate` when creating the picker, the selected date is today, so clicking today again is not a new selection and your callback doesn't fire. If you want to run some code every time the picker is closed even if the date selection hasn't changed, use the `apply` event instead of a callback.

**Comment by ramilani12** [comment]
Hi @dangrossman I am not populating my input in callback function.

**Comment by dangrossman** [comment]
Then it's going to stay blank forever, since that's what `autoUpdateInput: false` means. You have to write your own code to update the input.

**Comment by ramilani12** [comment]
There is no workaround? 
I tried this:

`$('#config-demo').on('apply.daterangepicker', function(ev,picker) {
				
			});`

**Comment by dangrossman** [comment]
That's an empty function, there's no code in it that does anything. You wanted to set the value of an input.

```
$('#config-demo').on('apply.daterangepicker', function(ev,picker) {
    $('#config-demo').val(picker.startDate.format('MM/DD/YYYY');
});
```

**Comment by ramilani12** [comment]
Yes @dangrossman my code was a simple example.
